from .grado import Grado
from .universidad import Universidad
from .tipodocumento import TipoDocumento
from .departamento import Departamento
from .alumno import Alumno
from .tipoespecialidad import TipoEspecialidad
from .tipodedicacion import TipoDedicacion
from .area import Area
from .especialidad import Especialidad
from .plan import Plan
from .materia import Materia
from .categoriacargo import CategoriaCargo
from .grupo import Grupo
from .cargo import Cargo
from .orientacion import Orientacion
from .autoridad import Autoridad
from .facultad import Facultad